const wordL = [
  ['sweep', 'to move, especially quickly and powerfully'],
  ['crack', 'to break something so that it does not separate, but very thin lines appear on its surface, or to become broken in this way'],
  ['enemy', 'a person who hates or opposes another person and tries to harm them or stop them from doing something'],
  ['obviously', 'in a way that is easy to understand or see'],
  ['pretend', 'to behave as if something is true when you know that it is not, especially in order to deceive people or as a game'],
  ['convinced', 'completely certain about something'],
  ['relive', 'to remember clearly an experience that happened in the past'],
  ['dunno', 'short form of I don\'t know'],
  ['magnificent', 'very good, beautiful, or deserving to be admired'],
  ['eerie', 'strange in a frightening and mysterious way'],
  ['thought', 'past simple and past participle of think'],
  ['though', 'but'],
  ['cheat', 'to behave in a dishonest way in order to get what you want'],
  ['disgusting', 'extremely unpleasant or unacceptable'],
  ['obvious', 'easy to see, recognize, or understand'],
  ['rage', '(a period of) extreme or violent anger'],
  ['roar with sth', 'to express an emotion, such as laughter or anger, noisily'],
  ['roar', 'to make a long, loud, deep sound'],
  ['rare', 'not common or frequent; very unusual'],
  ['yell', 'to shout something or make a loud noise, usually when you are angry, in pain, or excited'],
  ['glimpse', 'an occasion when you see something or someone for a very short time'],
  ['swoop', 'to move very quickly and easily through the air, especially down from a high position in order to attack'],
  ['indeed', 'really or certainly, often used to emphasize something'],
  ['backward', 'not advanced'],
  ['doorknob', 'a round handle that you turn to open a door'],
  ['nightmare', 'a very upsetting or frightening dream'],
  ['sleeve', 'the part of a piece of clothing that covers some or all of the arm'],
  ['snarl', '(especially of dogs) to make a deep, rough sound while showing the teeth, usually in anger or (of people) to speak or say something angrily and forcefully'],
  ['moan', 'to make a long, low sound of pain, suffering, or another strong emotion'],
  ['assemble', 'to make something by joining separate parts'],
  ['assemble', 'to come together in a single place or bring parts together in a single group'],
  ['struggle', 'to experience difficulty and make a very great effort in order to do something'],
  ['borrow', 'to get or receive something from someone with the intention of giving it back after a period of time'],
  ['ruin', 'to spoil or destroy something completely'],
  ['adorable', 'charming, attractive, and easily loved'],
  ['blink', 'When you blink, you close and then open your eyes quickly once or several times, and when an eye blinks, it does this'],
  ['limp', 'to walk slowly and with difficulty because of having an injured or painful leg or foot'],
  ['gullible', 'easily deceived or tricked, and too willing to believe everything that other people say'],
  ['otherwise', 'used after an order or suggestion to show what the result will be if you do not follow that order or suggestion'],
  ['care', 'the process of protecting someone or something and providing what that person or thing needs'],
  ['scallywag', 'someone, especially a child, who has behaved badly but who is still liked'],
  ['journal', 'a serious magazine or newspaper that is published regularly about a particular subject'],
  ['journal', 'a written record of what you have done each day, sometimes including your private thoughts and feelings'],
  ['goodness', 'the personal quality of being morally good'],
  ['at issue', 'most important in what is being discussed'],
  ['issue', 'a subject or problem that people are thinking and talking about'],
  ['at least', 'used to reduce the effect of a statement'],
  ['come up with sth', 'to suggest or think of an idea or plan'],
  ['so far', 'at this particular time'],
  ['whole', 'complete or not divided'],
  ['make a difference', 'to improve a situation'],
  ['moderate', 'neither small nor large in size, amount, degree, or strength'],
  ['vigorous', 'very forceful or energetic'],
  ['employ', 'to have someone work or do a job for you and pay them for it'],
  ['engage', 'to employ someone'],
  ['reduce', 'to become or to make something become smaller in size, amount, degree, importance, etc'],
  ['seal', 'a large mammal that eats fish and lives partly in the sea and partly on land or ice'],
  ['lean', 'to (cause to) slope in one direction, or to move the top part of the body in a particular direction'],
  ['irresistible', 'impossible to refuse, oppose, or avoid because it is too pleasant, attractive, or strong'],
  ['behold', 'to see or look at someone or something'],
  ['quit', 'to stop doing something or leave a job or a place'],
  ['increase', 'to (make something) become larger in amount or size'],
  ['drum up sth', 'to try to increase business activity or get support for something'],
  ['beware', 'used to warn someone to be very careful about something or someone'],
  ['discourse', 'communication in speech or writing'],
  ['conversation', '(a) talk between two or more people in which thoughts, feelings, and ideas are expressed, questions are asked and answered, or news and information is exchanged'],
  ['require', 'to need something or make something necessary'],
  ['flow', '(especially of liquids, gases, or electricity) to move in one direction, especially continuously and easily'],
  ['upset', 'to make someone worried, unhappy, or angry'],
  ['slightly', 'a little'],
  ['distinguish', 'to notice or understand the difference between two things, or to make one person or thing seem different from another'],
  ['throughout', 'in every part, or during the whole period of time'],
  ['whereas', 'compared with the fact that; but'],
  ['precisely', 'exactly, used to emphasize something'],
  ['emphasize', 'to show that something is especially important or needs special attention'],
  ['convenient', 'easy to use or suiting your plans well'],
  ['complaining', 'the act of saying that something is wrong or not satisfactory'],
  ['merely', 'used to emphasize that you mean exactly what you are saying and nothing more'],
  ['fairness', 'the quality of treating people equally or in a way that is right or reasonable'],
  ['justice', 'behaviour or treatment that is fair and morally correct'],
  ['poll', 'a study in which people are asked for their opinions about a subject or person'],
  ['probe', 'to try to discover information that other people do not want you to know, by asking questions carefully and not directly'],
  ['riddle', 'a type of question that describes something in a difficult and confusing way and has a clever or funny answer, often asked as a game'],
  ['threat', 'a suggestion that something unpleasant or violent will happen, especially if a particular action or order is not followed'],
  ['keen', 'very interested, eager, or wanting (to do) something very much'],
  ['terrified', 'very frightened'],
  ['calm', 'without hurried movement or noise'],
  ['irritated', 'annoyed'],
  ['reject', 'to refuse to accept, use, or believe something or someone'],
  ['full stop', 'the symbol . used in writing at the end of a sentence or at the end of the short form of a word'],
  ['refuse', 'to say that you will not do or accept something'],
  ['hurt', 'to feel pain in a part of your body, or to injure someone or cause them pain'],
  ['apologize', 'to tell someone that you are sorry for having done something that has caused problems or unhappiness for them'],
  ['lad', 'a boy or young man'],
  ['bite', 'to use your teeth to cut into something or someone'],
  ['pout', 'to push the lower lip forward to show you are annoyed, or to push both lips forward in a sexually attractive way'],
  ['chase', 'to hurry after someone or something in order to catch him, her, or it'],
  ['I beg your pardon', 'a polite way of saying "I am sorry" or "Could you repeat what you just said?"'],
  ['advisable', 'If something is advisable, it will avoid problems if you do it'],
  ['dishonest', 'not honest'],
  ['orphanage', 'a home for children whose parents are dead or unable to care for them'],
  ['case', 'a particular situation or example of something'],
  ['slip', 'to slide by accident and fall or almost fall'],
  ['a regret', 'сожаление'], ['fearfully', 'страшно'], ['a loony', 'полоумный'],
  ['a plank', 'доска'], ['illiterate', 'неграмотный'], ['a climber', 'альпинист'],
  ['completely', 'полностью'], ['goodly', 'красивый'], ['a crutch', 'опора'],
  ['a syllable', 'слог'], ['a torture', 'пытка'], ['run out of', 'израсходовать'],
  ['typical of', 'типичный для'], ['at least', 'по крайней мере'], ['the other side', 'другая жизнь'],
  ['be at someone\'s feet', 'быть у чьих-то ног'], ['be supposed to', 'быть должным (сделать что-либо)'],
  ['they say', 'говорят'], ['go over', 'обсуждать'], ['take for granted', 'принимать как должное'],
  ['throw on', 'надевать'], ['so far', 'на сегодняшний момент'], ['lose touch', 'потерять связь'],
  ['a rake', 'грабли'], ['peculiar', 'своеобразный'], ['to patch', 'латать'],
  ['to bewitch', 'заколдовывать'], ['mainly', 'главным образом'],
  ['to lead', 'приводить'], ['youth', 'молодость'],
  ['young', 'молодой'], ['a yard', 'двор'], ['in the middle of', 'посреди'],
  ['fish out of water', 'не в своей тарелке'],
  ['leave to chance', 'предоставить дело случаю'],
  ['nothing but', 'only.'], ['long for', 'тосковать'],
  ['ergo', 'следовательно'], ['run into', 'натыкаться'],
  ['be here to stay', 'войти во всеобщее употребление'],
  ['check out', 'выселяться'], ['turn on', 'включать'], ['look after', 'присматривать'],
  ['an egis', 'защита'], ['used to', 'раньше'],
  ['be off', 'удаляться'], ['break up', 'разрывать отношения'],
  ['stay on', 'оставаться'], ['be supposed to', 'быть должным (сделать что-либо)'],
  ['not half', 'совсем не'], ['break down', 'ломаться'],
  ['this way', 'таким образом'], ['watch out', 'быть осторожным'],
  ['a tyre', 'шина'], ['tabby', 'полосатый'],
  ['out there', 'где-то там'], ['check in', 'регистрироваться'], ['write down', 'записывать'],
  ['work out', 'тренироваться'], ['get along with', 'ладить'],
  ['fall apart', 'разваливаться на части'],
  ['look up', 'искать'], ['a coiner', 'фальшивомонетчик'],
  ['on and on', 'снова и снова'], ['To abolish', 'Отменять, уничтожать, упразднять'], ['To approve', 'Утвердить, одобрить'],
  ['To boast', 'Гордиться, хвастаться'],
  ['To contribute', 'Жертвовать, вносить свой вклад'], ['To deliver', 'Доставлять, поставлять, приносить'], ['To descend', 'Спуститься, сходить, снизойти'],
  ['To concentrate', 'Сосредотачиваться'], ['To distract', 'Отвлечь, отвлекать'], ['To torture', 'Мучить, терзать'],
  ['To confuse', 'Путать, запутать, сбить с толку'], ['To abandon', 'Покинуть, бросить, оставить'],
  ['To escape', 'Совершить побег, убежать, сбежать'], ['To distribute', 'Распространять, распределить'],
  ['To elaborate', 'Разрабатывать, прорабатывать'], ['To construct', 'Строить, построить'],
  ['To humiliate', 'Унижать'], ['To maintain', 'Поддерживать'],
  ['To squeeze', 'Сжимать, выжимать, сжать'],
  ['To delegate', 'Делегировать, посылать'],
  ['To transfer', 'Передавать, перечислять'],
  ['To employ', 'Нанимать, использовать, работать'],
  ['To catch', 'Поймать, ловить'],
  ['To commit', 'Совершить, зафиксировать, поручить'],
  ['To arrange', 'Организовать, устроить'],
  ['To implement', 'Внедрить, реализовать, осуществить'],
  ['To insulate', 'Ограждать'],
  ['To encourage', 'Стимулировать'],
  ['To foster', 'Поощрять'],
  ['To boost', 'Повышать'],
  ['To optimize', 'Оптимизировать'],
  ['To rank', 'Ранжировать'],
  ['To identify', 'Определить, идентифицировать'],
  ['To empower', 'Наделить полномочиями, расширять'],
  ['To ensure', 'Обеспечить, убедить, гарантировать'],
  ['To accomplish', 'Выполнить, завершить, осуществить'],
  ['To customize', 'Настроить, сделать'],
  ['To localize', 'Локализовать, определить'],
  ['To tailor', 'Приспособить'],
  ['To validate', 'Удостоверять'],
  ['To reserve', 'Резервировать'],
  ['To estimate', 'Оценивать'],
  ['To consulate', 'Консультировать'],
  ['To regard', 'Рассматривать, учитывать, относиться'],
  ['To indicate', 'Указывать, обозначать, показывать'],
  ['To unify', 'Объединять'],
  ['To digitalize', 'Оцифровать, перевести в online-формат'],
  ['To expose', 'Подвергать'],
  ['To idealize', 'Идеализировать'],
  ['To navigate', 'Ориентироваться'],
  ['To sustain', 'Выдерживать'],
  ['To constrain', 'Сдерживать'],
  ['To evade', 'Обойти'],
  ['To purchase', 'Приобретать'],
  ['To earn', 'Зарабатывать'],
  ['To make sure', 'Убедиться'],
  ['To prototype', 'Создать протопит, план'],
  ['To endeavour', 'Стремиться'],
  ['To blend', 'Смешивать'],
  ['To prioritize', 'Расставить приоритеты'],
  ['To mitigate', 'Смягчать, принимать'],
  ['To emphasize', 'Подчеркнуть, придать акцент'],
  ['To observe', 'Наблюдать, замечать'],
  ['To evolve', 'Развиваться, расти, проявляться'],
  ['To incentivize', 'Стимулировать, побуждать'],
  ['To respond', 'Реагировать, отвечать'],
  ['To connect', 'Соединить'],
  ['To command', 'Командовать',]
  ['To check-out', 'Проверить, ,оформить'],
  ['To extend', 'Продлить, расширить, увеличить'],
  ['To retain', 'Оставить, удержать, сохранить'],
  ['To exhibit', 'Показывать'],
  ['To invent', 'Изобретать'],
  ['To abridge', 'Ограничивать'],
  ['To self-express', 'Самовыражаться'],
  ['To neglect', 'Пренебрегать'],
  ['To negotiate', 'Договариваться, вести переговоры'],
  ['To upgrade', 'Повышать, улучшать'],
  ['To renew', 'Обновить'],
  ['To specialize', 'Специализироваться'],
  ['To balance', 'Уравновешивать'],
  ['To absorb', 'Поглощать'],
  ['To overwhelm', 'Переполнять'],
  ['To align', 'Выравнивать'],
  ['To withdraw', 'Отстраниться'],
  ['To whistle', 'Свистеть'],
  ['To suspect', 'Подозревать'],
  ['To surrender', 'Сдаваться'],
  ['To depend on', 'Зависеть от'],
  ['To correct', 'Исправлять'],
  ['To define', 'Определить'],
  ['To visualize', 'Визуализировать'],
  ['To design', 'Проектировать'],
  ['To minimize', 'Минимизировать'],
  ['To disturb', 'Нарушить, беспокоить'],
  ['To integrate', 'Интегрировать'],
  ['To exchange', 'Обменивать, менять'],
  ['Toorganize', 'Организовать'],
  ['To collaborate', 'Сотрудничать'],
  ['To embed', 'Встраивать'],
  ['To generate', 'Генерировать'],
  ['addiction', 'Зависимость, пристрастие'],
  ['amateur', 'Любитель'],
  ['ambivalence', 'Нерешительность'],
  ['commission', 'Комиссия, поручение, заказчик'],
  ['confidence', 'Доверие, уверенность, достоверность'],
  ['craving', 'Желание, тяга, стремление, жажда'],
  ['district', 'Район'],
  ['evidence', 'Доказательство, признак, факт'],
  ['honesty', 'Честность'],
  ['circumstance', 'Обстоятельство, случай, событие'],
  ['kindness', 'Доброта'], ['justice', 'Справедливость'],
  ['disgust', '	Отвращение, брезгливость'],
  ['suggestion', 'Предложение, суждение, идея'],
  ['nobility', 'Благородство, достоинство'],
  ['commotion', 'Суета'], ['adherence', 'Приверженность'],
  ['devotion', 'Преданность'],
  ['enticement', 'Приманка, соблазн, заманивание'],
  ['attractiveness', 'Привлекательность'],
  ['freedom-loving', 'Свободолюбие'],
  ['rebel', 'Бунтарь'], ['influence', 'Влияние'],
  ['sway', 'Колебание'], ['willpower', 'Сила воли'],
  ['inequality', 'Неравенство'],
  ['violence', 'Насилие, жестокость'],
  ['bullying', 'Издевательство, травля'],
  ['godliness', 'Благочестие, бодрость'],
  ['compassion', 'Сострадание'],
  ['inclusivity', 'Инклюзивность'],
  ['reciprocity', 'Взаимность, обоюдность'],
  ['friskiness', 'Игривость, раскованность, живость'],
  ['fervor', 'Пылкость, задор, рвение'],
  ['youth', 'Молодежь, юноша, молодость'],
  ['adolescence', 'Подростковый возраст, отрочество'],
  ['prerequisite', 'Предпосылка, условие'],
  ['fortune', 'Судьба, удача, желание, успех'],
  ['Stubbornness', 'Упрямость'],
  ['disappointment', 'Разочарование'],
  ['distancing', 'Дистанцирование'],
  ['isolation', 'Изоляция'],
  ['self-care', 'Забота о себе'],
  ['medication', 'Лекарство'],
  ['celebration', 'Мероприятие'],
  ['physician', 'Врач, доктор, терапевт'],
  ['treatment', 'Лечение'], ['improvement', 'Улучшение'],
  ['symptom', 'Симптом'], ['dismay', 'Огорчение'],
  ['cancellation', 'Отмена'], ['suspiciousness', 'Подозрительность'],
  ['escalation', 'Обострение, эскалация'],
  ['proceeding', 'Разбирательство'],
  ['awareness', 'Осознание'], ['responsibility', 'Ответственность'],
  ['aftermath', 'Последствие'], ['weakness', 'Слабость'],
  ['rivalry', 'Соперничество, противостояние'],
  ['restlessness', 'Беспокойство'],
  ['uncertainty', 'Неуверенность, неопределенность'],
  ['stress resistance', 'Стрессоустойчивость'],
  ['conscience', 'Совесть'],
  ['А mindfulness', 'Внимательность, мышление, осознанность'],
  ['protection', 'Защита, протекция'],
  ['referral', 'Направление'], ['hopelessness', 'Безнадежность'],
  ['reliability', 'Надежность'], ['verification', 'Проверка'],
  ['self-isolation', 'Самоизоляция'],
  ['provocation', 'Провокация'],
  ['prevention', 'Профилактика'],
  ['side effect', 'Побочный эффект'],
  ['vaccination', 'Вакцинация'],
  ['immunization', 'Иммунизация'],
  ['contradiction', 'Противоречие'],
  ['emotion', 'Эмоция'], ['disagreement', 'Разногласие'],
  ['misunderstanding', 'Недоразумение, недопонимание'],
  ['negotiation', 'Переговоры'],
  ['downfall', 'Падение, упадок, крах, понижение'],
  ['setback', 'Неудача, провал'],
  ['bad luck', 'Невезение, несчастье'],
  ['depression', 'Депрессия'],
  ['solitude', 'Одиночество'],
  ['self-blame', 'Самобичевание'],
  ['disorder', '	Расстройство, разлад'],
  ['instability', '	Нестабильность'],
  ['challenge', '	Вызов, сложность'],
  ['sustainability', 'Устойчивость, жизнеспособность'],
  ['duration', 'Продолжительность'],
  ['luckiness', 'Удачливость, везение'],
  ['fluke', 'Случайность, шанс'],
  ['winning', 'Выигрыш, победа, завоевание'],
  ['lottery', 'Лотерея'], ['destination', 'Предназначение'],
  ['advantage', 'Преимущество'], ['win', 'Победа, выигрыш']
  ['condition', 'Условие, обстоятельство, состояние'],
  ['contest', 'Соревнование, борьба, конкурс'],
  ['humbleness', 'Смирение, скромность, покорность'],
  ['fearlessness', 'Бесстрашие'],
  ['hardening', 'Закалка, твердость'],
  ['buoyancy', 'Оживленность, жизнелюбие'],
  ['cheerfulness', 'Жизнерадостность, веселость'],
  ['hospitality', 'Гостеприимство, радушие'],
  ['pessimism', 'Пессимизм'], ['morale', 'Мораль, дух, нрав, мужество'],
  ['wisdom', 'Мудрость'], ['proficiency', 'Мастерство, умение, квалификация'],
  ['applicant', 'Претендент, соискать, заявитель'],
  ['decisiveness', 'Решительность'], ['loophole', 'Лазейка, дыра'],
  ['frustration', 'Фрустрация, разочарование'],
  ['knowledge', 'Знание, познание'], ['decision-making', 'Принятие решения'],
  ['alacrity', 'Аккуратность, активность, стремительность'],
  ['extremity', 'Крайность, упорство, чрезмерность'],
  ['background', 'Фон, предпосылка'],
  ['preparatory', 'Подготовка'], ['Arrogant', 'Высокомерный, заносчивый'],
  ['Civilian', 'Гражданский'], ['Commercial', 'Коммерческий'],
  ['Convenient', 'Удобный'], ['Creative', 'Креативный, творческий'],
  ['Naughty', 'Озорной, шаловливый'], ['Stationary', 'Стационарный'],
  ['Valuable', 'Ценный'], ['Significant', 'Значительный, существенный'],
  ['Foremost', 'Передовой, основной, главный'],
  ['Recent', 'Недавний'], ['Updated', 'Обновленный'],
  ['Operational', 'Оперативный, рабочий, действующий'],
  ['Intuitive', 'Интуитивно понятный, интуитивный'],
  ['Essential', 'Существенный, важный'],
  ['Numerous', 'Многочисленный'], ['Compliant', 'Соответствующий'],
  ['Straightforward', 'Прямой, прямолинейный'],
  ['Understandable', 'Понятный, доступный'],
  ['Uncompromising', 'Беспрекословный'],
  ['Distinguished', 'Выдающийся, уважаемый, отличительный'],
  ['Separate', 'Отдельный'], ['Outstanding', 'Незаурядный'],
  ['Principal', 'Принципиальный, главный'],
  ['Leading', 'Ведущий, лидирующий'],
  ['Cognitive', 'Когнитивный, познавательный'],
  ['Cutting-edge', 'Современный, новейший'],
  ['Precise', 'Точный, четкий'], ['Unmatched', 'Неповторимый, непревзойденный'],
  ['Reasonable', 'Разумный, целесообразный'],
  ['Fundamental', 'Основополагающий'],
  ['Brilliant', 'Блестящий, гениальный'],
  ['Inflexible', 'Несгибаемый, непогрешимый'],
  ['Crucial', 'Решающий, критический, важный'],
  ['Contemporary', 'Современный, актуальный'],
  ['Duplicated', 'Дублированный'],
  ['Tedious', 'Утомительный, кропотливый, надоедливый'],
  ['Multiple', 'Множественный, многочисленный'],
  ['Individual', 'Личный, индивидуальный'],
  ['Fitting', 'Подходящий'], ['Monotonous', 'Монотонный, однообразный'],
  ['Ruthless', 'Бесчеловечный'], ['Multi-channel', 'Многоканальный'],
  ['Astonishing', 'Удивительный, изумительный'],
  ['Ambitious', 'Амбициозный, честолюбивый'],
  ['Captivating', 'Захватывающий, завораживающий'],
  ['Profound', 'Глубокомысленный'], ['Qualified', 'Квалифицированный'],
  ['Remarkable', 'Замечательный, примечательный, выдающийся'],
  ['Additional', 'Дополнительный'],
  ['Burning', 'Горящий, жгучий'], ['Unassuming', 'Непритязательный'],
  ['Meaningful', 'Значимый, осмысленный'],
  ['Private', 'Личный, частный'], ['Careful', 'Бережный, осторожный'],
  ['Obscure', 'Наблюдательный, непонятный'],
  ['Accomplished', 'Состоятельный, успешный, достигнутый'],
  ['Ridiculous', 'Нелепый, смешной'], ['Contemptuous', 'Презрительный'],
  ['Fashionable', 'Модный'], ['Invariably', 'Неизменно'],
  ['Intermittently', 'Иногда'], ['Infrequently', 'Редко'],
  ['Predominantly', 'Постоянно'], ['Elsewhere', 'Где-нибудь'],
  ['Scarcely', 'Едва'], ['Otherwise', 'Иначе'],
  ['Quickly', 'Быстро'], ['Quietly', 'Спокойно, тихо'],
  ['Moreover', 'Более того'], ['Nevertheless', 'Тем не менее'],
  ['Somewhat', 'До некоторой степени'],
  ['Cheerfully', 'Весело'], ['Clumsily', '	Неуклюже'],
  ['In vain', '	Напрасно'], ['At once', '	Немедленно'],
  ['Casually', 'Случайно'], ['Since that', 'С тех пор'],
  ['By all means', 'Во что бы то нистало'],
  ['Readily', 'Охотно'], ['Outside', 'Снаружи'],
  ['Besides', 'Кроме того'], ['Once', 'Однажды'],
  ['However', 'Однако, как бы ни'],
  ['Yet', 'Еще, до сих пор'], ['Foolishly', 'Глупо, по глупости'],
  ['Clearly', 'Очевидно'], ['Actually', 'В общем, вообще-то'],
  ['Completely', '	Совершенно, абсолютно'],
  ['Extremely', 'Безумно'], ['Nearby', 'Рядом, неподалеку'],
  ['Unmistakable', 'Безошибочно'],
  ['Accurately', 'Точно'], ['Definitely', 'Абсолютно'],
  ['Relentlessly', 'Безостановочно'],
  ['Incredibly', 'Невероятно, очень, неимоверно'],
  ['Decidedly', 'Решительно'], ['Firmly', 'Уверенно'],
  ['Carelessly', 'Беспечно'], ['Nevertheless', 'Тем не менее']
]

//
const frasVerbs = [
  ['add on', 'прибавлять'],
  ['add up', 'складывать'],
  ['answer back', 'огрызаться'],
  ['answer to', 'быть подотчетным или ответственным перед'],
  ['attend to', 'обслуживать'],
  ['back out', 'отступаться/сдавать назад'],
  ['back up', 'двигаться назад (тр.ср-во)/отменить действия/пересмотреть мысли'],
  ['bank on', 'полагаться на'],
  ['bear out', 'поддерживать'],
  ['bear up', 'держаться'],
  ['beat down', 'палить(о солнце)'],
  ['belt out', 'горланить'],
  ['belt up', 'заткнуться'],
  ['blast off', 'взлетать, взмывать'],
  ['blot out', 'заслонять'],
  ['blow out', 'гаснуть'],
  ['blow over', 'проходить, миновать'],
  ['boil down to', 'сводиться к чему-либо'],
  ['book in', 'регистрироваться'],
  ['bottle up', 'держать в себе, сдерживать, скрывать'],
  ['box off', 'окружать'],
  ['break down', 'сломаться'],
  ['break in', 'вламываться'],
  ['break off', 'прерывать, расторгать'],
  ['break open', 'взламывать'],
  ['break out', 'сбегать из тюрьмы, школы'],
  ['break through', 'прорываться сквозь'],
  ['bring about', 'вызывать (авариваю)'],
  ['bring back', 'вернуть, принести назад'],
  ['bring down', 'сбить, снижать, свалить'],
  ['bring forward', 'выдвигать'],
  ['bring in', 'включать, привлечь, вводить'],
  ['bring off', 'заключать'],
  ['bring out', 'выявлять'],
  ['bring round', 'приводить в чувство'],
  ['brush aside', 'отметать'],
  ['brush past', 'проноситься мимо'],
  ['brush up', 'освежать'],
  ['build on', 'пользоваться'],
  ['build up', 'наращивать'],
  ['bump along', 'трястись по'],
  ['bump into', 'наталкиваться на'],
  ['bundle off', 'отсылать'],
  ['bundle out', 'быстро уходить'],
  ['burst into', 'врываться'],
  ['burst open', 'распахиваться'],
  ['burst out', 'разразиться'],
  ['buy in', 'закупать'],
  ['buy into', 'входить в долю'],
  ['buy off', 'подкупать'],
  ['buy out', 'выкупать долю'],
  ['buy up', 'скупать'],
  ['buzz off', 'отваливать'],
  ['call at', 'приходить с визитом; приходить в гости; останавливаться в'],
  ['call back', 'заходить опять, перезванивать'],
  ['call for', 'призывать к'],
  ['call off', 'отменять'],
  ['call on', 'призывать, навещать, апеллировать, звонить по телефону'],
  ['call out', 'кричать'],
  ['carry on', 'продолжать'],
  ['carry out', 'кричать'],
  ['cast aside', 'отвергать'],
  ['catch on', 'приживаться'],
  ['catch up', 'нагонять'],
  ['catch up with', 'догнать кого-либо'],
  ['chase up', 'напоминать'],
  ['chat up', 'заигрывать'],
  ['check in', 'регистрироваться'],
  ['check off', 'отмечать'],
  ['check out', 'выписываться'],
  ['check up on', 'наводить справки'],
  ['cheer up', 'ободрять'],
  ['chill out', 'кайфовать'],
  ['chip in', 'вмешиваться, принимать участие'],
  ['clear off', 'убираться (убирайся отсюда)'],
  ['climb down', 'слезать, уступать, отступать'],
  ['to close in on something', 'становиться ближе к'],
  ['close off', 'огораживать'],
  ['come across', 'наталкиваться'],
  ['come along', 'продвигаться'],
  ['come apart', 'разваливаться'],
  ['come forward', 'вызываться'],
  ['come off', 'отрываться'],
  ['come on', 'продвигаться'],
  ['come around', 'приходить в себя'],
  ['come through', 'проникать, перенести, проходить внутрь, проходить насквозь'],
  ['come up against', 'сталкиваться с; конфликтовать;'],
  ['come up with', 'придумывать'],
  ['cool down', 'остудить пыл'],
  ['count on', 'рассчитывать на'],
  ['cover up', 'прикрывать, покрывать кого-либо'],
  ['crack down on', 'расправляться с'],
  ['crack up', 'лопаться от смеха'],
  ['cross out', 'вычеркивать'],
  ['cut off', 'отключать'],
  ['cut out', 'вырезать, выключать, выкраивать, вытеснять'],
  ['deal in', 'торговать'],
  ['die away', 'замирать(о звуке)'],
  ['die down', 'угасать'],
  ['dig into', 'зарываться; закапывать'],
  ['do away with', 'покончить с'],
  ['do up', 'завязывать, застегивать'],
  ['do without', 'обходиться без'],
  ['double back', 'возвращаться по собственным следам'],
  ['double up', 'сгибаться пополам'],
  ['draw in', 'вовлекать, сокращаться(день), близиться к концу'],
  ['draw on', 'использовать'],
  ['draw out', 'растягивать'],
  ['draw up', 'составлять/набрасывать (план и т. д.)'],
  ['dream up', 'выдумывать'],
  ['dress up', 'наряжаться'],
  ['drink in', 'упиваться'],
  ['drive off', 'отбрасывать'],
  ['drive out', 'вытеснять'],
  ['drop in', 'заглядывать к кому-либо'],
  ['drum up', 'призывать'],
  ['dwell on', 'зацикливаться на'],
  ['ease off', 'становиться тише, замедляться'],
  ['eat away at', 'разъедать'],
  ['eat out', 'есть в ресторане'],
  ['explain away', 'находить оправдание'],
  ['fade out', 'постепенно уменьшать, ослаблять'],
  ['fall apart', 'разваливаться по частям'],
  ['fall back on', 'прибегать к'],
  ['fall behind', 'отставать'],
  ['fall for', 'влюбляться в'],
  /* ['fall in with', 'соглашаться с'],*/
  ['focus on', 'сосредотачиваться на'],
  /*['feel about', 'искать на ощупь'],*/
  /* ['fetch up', 'оказаться'],*/ //turn out
  ['fiddle with', 'вертеть на руках'],
  ['fight back', 'мстить'],
  ['fight down', 'подавлять'],
  ['figure out', 'вычислять понимать'],
  ['fill in', 'пломбировать зуб'],
  ['filter in', 'просачиваться'],
  ['find out', 'узнавать, разоблачать'],
  ['finish up', 'доедать, допивать'],
  ['fish out', 'выуживать'],
  ['fit in', 'вписываться'],
  ['fix up', 'устраивать'],
  ['flick through', 'просматривать'],
  ['float around', 'носиться в воздухе'],
  ['flush out', 'спугнуть'],
  ['follow out', 'приводить в исполнение'],
  ['follow up', 'расследовать'],
  ['fool about', 'валять дурака'],
  ['force back', 'отражать натиск'],
  ['forge ahead', 'вырываться вперед'],
  ['fork out', 'выкладывать'],
  ['frown on', 'смотреть с неодобрением'],
  ['fuss over', 'трястись над'],
  ['gasp out', 'выпаливать'],
  ['get about', 'распространяться'],
  ['get across', 'объяснять'],
  ['get along', 'ладить'],
  ['get at', 'придираться'],
  ['get away', 'уходить'],
  ['get away with', 'избежать наказания'],
  ['get by', 'проходить'],
  ['get off', 'сходить с транспорта'],
  ['get on', 'садиться в транспорт'],
  ['get on to', 'переходить к'],
  ['get out of', 'отделываться от'],
  ['get over', 'преодолевать'],
  ['get round to', 'собираться сделать что-либо'],
  ['get through', 'дозвониться, прорваться'],
  ['get up', 'подниматься, вставать с постели'],
  ['get up to', 'заниматься'],
  ['give in', 'подчиниться'],
  ['give off', 'дымить'],
  ['give up', 'отказываться, сдаваться'],
  ['go about', 'прохаживаться'],
  ['go ahead', 'продвигаться'],
  ['go back on', 'не сдерживать'],
  ['go for', 'добиваться'],
  ['go in for', 'принимать участие'],
  ['go on', 'продолжать'],
  ['go on at', 'приставать к'],
  ['go through with', 'осуществлять'],
  ['go with', 'соответствовать'],
  ['go without', 'оставаться без'],
  ['grow apart', 'отдаляться друг от друга'],
  ['grow up', 'взрослеть'],
  ['hang about', 'слоняться'],
  ['hang on', 'подождать'],
  ['hang up', 'вешать трубку'],
  ['happen on', 'натыкаться на'],
  ['head for', 'направляться к'],
  ['head off', 'отводить'],
  ['hit on', 'отыскивать'],
  ['hit out at', 'набрасываться'],
  ['hold back', 'придерживать'],
  ['hold on', 'держаться ждать'],
  ['hold on to', 'держаться за'],
  ['hold out', 'протягивать'],
  ['hold over', 'откладывать'],
  ['hold up', 'поднимать поддерживать'],
  ['hurry up', 'торопить'],
  ['hush up', 'умалчивать'],
  ['inquire into', 'расследовать'],
  ['iron out', 'улаживать'],
  ['jog along', 'медленно продвигаться'],
  ['jump about', 'суетиться'],
  ['jump at', 'ухватываться за'],
  ['keep away from', 'держаться подальше от'],
  ['keep down', 'сдерживать'],
  ['keep in', 'держать дома'],
  ['keep off', 'обходить избегать'],
  ['keep out', 'не впускать'],
  ['keep up', 'поддерживать'],
  ['knock about', 'околачиваться'],
  ['knock off', 'закругляться'],
  ['knock out', 'оглушать'],
  ['ladle out', 'раздавать направо и налево'],
  ['land up', 'очутиться'],
  ['launch into', 'пускаться в'],
  ['lay in', 'запасать'],
  ['lay into', 'набрасываться на'],
  ['lay off', 'увольнять'],
  ['lay on', 'устраивать'],
  ['lay out', 'раскладывать'],
  ['lead off', 'отходить от'],
  ['lead on', 'водить за нос'],
  ['leave behind', 'забыть что-либо'],
  ['leave off', 'не включать'],
  ['leave on', 'не снимать'],
  ['leave out', 'пропускать оставлять без внимания'],
  ['let on', 'проговариваться'],
  ['let out', 'выпускать'],
  ['let up', 'переставать'],
  ['lie about', 'валяться'],
  ['lie back', 'откидываться'],
  ['lie up', 'скрываться'],
  ['live down', 'заглаживать'],
  ['live up to', 'оправдывать, доходить до какого-либо уровня'],
  ['lock away', 'заключать под стражу'],
  ['log in', 'входить в систему'],
  ['log into', 'входить в'],
  ['log off', 'выходить из системы'],
  ['look after', 'заботиться о'],
  ['look around', 'осматриваться'],
  ['look down on', 'смотреть свысока на'],
  ['look for', 'искать'],
  ['look forward to', 'ждать чего-либо с нетерпением'],
  ['look into', 'расследовать'],
  ['look on', 'наблюдать'],
  ['look out for', 'остерегаться'],
  ['look through', 'просматривать'],
  ['look up', 'находить информацию'],
  ['look up to', 'почитать'],
  ['make for', 'направляться к'],
  ['make off', 'скрываться'],
  ['make out', 'различать'],
  ['make up', 'составлять делать макияж'],
  ['make up for', 'восполнять'],
  ['mark down', 'снижать, уценивать'],
  ['mark off', 'отмечать'],
  ['mark out', 'размечать, выделять'],
  ['mark up', 'повышать, добавлять стоимость'],
  ['measure up', 'оправдывать'],
  ['mix up', 'путать'],
  ['mount up', 'накапливаться'],
  ['muddle along', 'справляться, кое-как'],
  ['muddle through', 'выкарабкиваться'],
  ['nod off', 'задремать'],
  ['pack off', 'отправлять'],
  ['pass away', 'на'],
  ['pass by', 'проходить, проезжать мимо'],
  ['pass out', 'терять сознание'],
  ['pass up', 'упускать'],
  ['patch up', 'улаживать'],
  ['pick at', 'ковырять'],
  ['pick off', 'методично сбивать, отстреливать'],
  ['pick on', 'придираться к'],
  ['pick out', 'разглядеть'],
  ['play down', 'не заострять внимание на'],
  ['play up', 'барахлить'],
  ['plug in', 'включать в розетку'],
  ['polish off', 'покончить с'],
  ['pop in', 'заглядывать, заскакивать к кому-нибудь'],
  ['pop out', 'выскакивать'],
  ['pop up', 'вылезать'],
  ['pour into', 'устремляться в'],
  ['press ahead', 'приступать к делу'],
  ['press on', 'продолжать'],
  ['pull about', 'трепать'],
  ['pull up', 'подтягивать'],
  ['push in', 'влезать'],
  ['push off', 'убираться'],
  ['push on', 'двигаться вперед'],
  ['push over', 'опрокидывать'],
  ['push up', 'повышать'],
  ['put across', 'объяснять'],
  ['put by', 'откладывать'],
  ['put forth', 'объявлять'],
  ['put forward', 'выдвигать, переводить вперед'],
  ['put in for', 'подавать заявление на'],
  ['put on', 'надевать'],
  ['put out', 'тушить, выключать'],
  ['put through', 'соединять, выполнять соединение'],
  ['put up with', 'терпеть, мириться с'],
  ['reach out', 'протягивать'],
  ['reflect on', 'бросать тень на'],
  ['root about', 'рыться'],
  ['root for', 'болеть за'],
  ['root out', 'откопать'],
  ['round off', 'завершать'],
  ['round up', 'округлять'],
  ['rule out', 'исключать'],
  ['run across', 'натыкаться на'],
  ['run down', 'сокращать, сбивать'],
  ['run into', 'сталкиваться с'],
  ['run off', 'сбегать, убегать'],
  ['run out', 'истекать, заканчиваться'],
  ['run over', 'задавить'],
  ['rush through', 'делать в спешке'],
  ['score out', 'вычеркивать'],
  ['scrape together', 'наскребать'],
  ['screw up', 'комкать, портачить'],
  ['see about', 'заниматься'],
  ['see off', 'провожать'],
  ['see through', 'доводить до конца'],
  ['see to', 'позаботиться о'],
  ['seize up', 'глохнуть'],
  ['send for', 'заказывать'],
  ['send in', 'подавать заявление о'],
  ['send up', 'запускать'],
  ['serve out', 'раскладывать'],
  ['set about', 'приступать к'],
  ['set back', 'задерживать'],
  ['set off', 'отправляться'],
  ['set up', 'учреждать'],
  ['shoot down', 'сбивать'],
  ['shoot in', 'стремглав вбегать'],
  ['shoot out', 'стремглав выбегать'],
  ['shoot up', 'подскакивать'],
  ['shop around', 'прицениваться'],
  ['shout down', 'заглушать криками'],
  ['show in', 'проводить внутрь'],
  ['show off', 'отмахиваться от'],
  ['show out', 'провожать к выходу'],
  ['show up', 'виднеться появляться'],
  ['shrug off', 'отмахиваться от'],
  ['shut off', 'отключать'],
  ['shut out', 'не пропускать'],
  ['shut up', 'заткнуться'],
  ['sign away', 'передавать'],
  ['sign in', 'регистрироваться'],
  ['sign off', 'заканчивать'],
  ['sign out', 'выписываться'],
  ['sign up', 'наниматься, подписаться'],
  ['skate around', 'обходить'],
  ['skate over', 'игнорировать'],
  ['sleep around', 'спать с кем попало'],
  ['sleep in', 'просыпать, отсыпаться'],
  ['slip up', 'ошибаться'], ['smooth over', 'улаживать дела'],
  ['sound off', 'высказаться о'],
  ['square up', 'поквитаться с кем-либо'],
  ['stamp out', 'затаптывать'], ['stand by', 'быть на готове'],
  ['stand down', 'уступать место'], ['stand for', 'обозначать, представлять'],
  ['stand in for', 'замещать'], ['stand up for', 'отстаивать'],
  ['stand up to', 'выдерживать'], ['stem from', 'происходить от'],
  ['stick up for', 'заступаться за'],
  ['stir up', 'вызывать'], ['stop by', 'заходить'],
  ['stop up', 'заделывать'], ['strike out', 'вычеркивать'],
  ['take after', 'пойти в кого-либо'],
  ['take down', 'снимать, убирать'],
  ['take in', 'включать в себя'], ['take off', 'взлетать'], ['take on', 'брать на себя'],
  ['take over', 'принимать руководство'],
  ['take to', 'пристраститься к'], ['take up', 'заняться, подхватить'],
  ['tear along', 'нестись'], ['tell off', 'отчитывать кого-либо'],
  ['tell on', 'жаловаться на'], ['think up', 'придумывать'],
  ['throw up', 'тошнить со рвотой'], ['touch on', 'затрагивать'],
  ['touch up', 'подкрашивать'], ['try on', 'мерить, примерить'],
  ['tuck away', 'припрятывать'], ['tuck in', 'заправлять, запихивать'],
  ['tuck up', 'укрывать'], ['turn down', 'отклонять'],
  ['turn in', 'сворачивать'], ['turn off', 'выключать'],
  ['turn on', 'включать'], ['turn up', 'объявляться'],
  ['wait on', 'обслуживать'], ['walk out on', 'бросать'],
  ['wash up', 'мыть посуду'], ['wear off', 'постепенно проходить'],
  ['wear on', 'тянуться'], ['work out', 'удаваться, срабатывать'],
  ['write off', 'списывать, аннулировать'], ['write up', 'приводить в порядок']
]
//
const phrases = [
  ['How is it going?', 'Как идут дела?'],
  ['How\'s life?', '	Как жизнь?'],
  ['How are things?', 'Как оно?'],
  ['Long time no see!', 'Давно не виделись!'],
  ['What are you up to?', 'Чем занимаешься?'],
  ['What have you been up to?', 'Чем занимался все это время?'],
  ['See you soon!', 'До скорого!'],
  ['See you later!', 'Увидимся позже!'],
  ['Till next time!', 'До следующего раза!'],
  ['Good luck!', 'Удачи!'],
  ['Take care!', 'Береги себя!'],
  ['Talk to you later!', 'Поговорим с тобой позже!'],
  ['Until we meet again!', 'До новой встречи!'],
  ['Have a nice day!', 'Хорошего дня!'],
  ['Have a good weekend', 'Хороших выходных'],
  ['Have a safe trip', 'Хорошей поездки'],
  ['Say hi to …', 'Передавай привет …'],
  ['Send my love to…', 'Передавай большой привет … (если речь идет о близких людях)'],
  ['In short / in brief', 'вкратце'],
  ['In a word', '	в двух словах'],
  ['As far / as to', 'что касается'],
  ['Not to mention', 'не говоря уже о'],
  ['First of all/above all', 'прежде всего'],
  ['What’s more', 'кроме того'],
  ['By the way', 'кстати'],
  ['After all', 'в итоге; все-таки'],
  ['Just for the record', 'для справки; чтобы вы знали'],
  ['And so on and so forth', 'и так далее'],
  ['If I’m not mistaken', 'если я не ошибаюсь'],
  ['In other words', 'другими словами'],
  ['On the contrary', 'наоборот'],
  ['The thing is', 'дело в том, что'],
  ['So as to / so that', 'так чтобы'],
  ['Either way', 'так или иначе'],
  ['As a rule', 'обычно, как правило'],
  ['As well as', 'так же, как и'],
  ['All the same', 'без разницы'],
  ['On one hand', 'с одной стороны'],
  ['On the other hand', 'с другой стороны'],
  ['Such as', 'например'],
  ['As I said before', 'как я уже говорил'],
  ['Believe it or not, but', 'верите или нет, но'],
  ['If I remember rightly / If I recall correctly', 'если я правильно помню'],
  ['Perhaps', 'Возможно, может быть'],
  ['Of courseSure', 'Конечно'],
  ['Definitely', 'Определенно, непременно'],
  ['Absolutely', 'Безусловно'],
  ['Naturally', 'Естественно'],
  ['Probably', 'Вероятно'],
  ['You are right', 'Вы правы'],
  ['It can hardly be so', 'Вряд ли это так'],
  ['Very well', 'Очень хорошо'],
  ['Most likely', 'Скорее всего'],
  ['Most unlikely', 'Вряд ли'],
  ['Not a bit', 'Ничуть'],
  ['I believe so / suppose so', 'Полагаю, что это так'],
  ['I doubt it', 'Сомневаюсь'],
  ['No way', 'Ни за что, ни в коем случае'],
  ['Exactly so', 'Именно так'],
  ['Quite so', 'Вполне верно'],
  ['I agree with you', 'Я с вами согласен'],
  ['I am afraid you are wrong', '	Боюсь, что вы не правы'],
  ['I’m afraid so', 'Боюсь, что так'],
  ['I’m not sure', 'Не уверен'],
  ['I don’t think so', 'Я так не думаю; вряд ли'],
  ['In a way / to a certain extent', 'В каком-то смысле'],
  ['No doubt', 'Несомненно'],
  ['I’m in / I’m game', 'Я «за» (в ответ на предложение что-либо сделать)'],
  ['I think I’ll pass', 'Лучше без меня'],
  ['Deal!', 'Идет!'],
  ['It’s a great idea!', 'Отличная идея!'],
  ['Not a very good idea', 'Не самая хорошая идея'],
  ['I\'m looking forward to it', 'Жду этого с нетерпением'],
  ['I’m so sorry!', 'Мне очень жаль!'],
  ['I beg your pardon!', 'Прошу прощения!'],
  ['I’m sorry, I can’t.', 'Простите, не могу.'],
  ['Sorry, I meant well.', 'Извините, я хотел как лучше.'],
  ['It’s very kind of you!', 'Это очень мило с вашей стороны!'],
  ['Thank you anyway!', '	В любом случае, спасибо!'],
  ['Thank you in advance!', 'Спасибо заранее!'],
  ['Don’t mention it!', '	Не стоит благодарности!'],
  ['May I help you?', '	Могу ли я вам помочь?'],
  ['No problem / that’s ok!', 'Все в порядке!'],
  ['Don’t worry about it!', 'Не волнуйтесь об этом!'],
  ['This way, please!', '	Сюда, пожалуйста!'],
  ['After you!', 'После вас!'],
  ['What’s the matter?', 'В чем дело?'],
  ['What’s going on? / What’s happening?', '	Что происходит?'],
  ['What’s the trouble?', 'В чем проблема?'],
  ['What’s happened?', 'Что случилось?'],
  ['How was it?	Ну как?', '(Как все прошло?)'],
  ['Did I get you right?', 'Я правильно вас понял?'],
  ['Don’t take it to heart.', 'Не принимайте близко к сердцу.'],
  ['I didn’t catch the last word.', 'Я не понял последнее слово.'],
  ['Sorry, I wasn’t listening.', 'Извините, я прослушал.'],
  ['It doesn’t matter.', 'Это не имеет значения.'],
  ['It is new to me.', '	Это новость для меня.'],
  ['Let us hope for the best.', 'Будем надеяться на лучшее.'],
  ['May I ask you a question?', 'Можно задать вам вопрос?'],
  ['Next time lucky!', 'Повезет в следующий раз!'],
  ['Oh, that. That explains it.', 'Вот оно что, это все объясняет.'],
  ['Say it again, please.', '	Повторите еще раз, пожалуйста.'],
  ['So that’s where the trouble lies!', '	Так вот в чем дело!'],
  ['Things happen.', '	Всякое бывает.'],
  ['What do you mean?', 'Что вы имеете в виду?'],
  ['Where were we?', 'На чем мы остановились?'],
  ['You were saying?', '	Вы что-то сказали?'],
  ['I’m sorry, I didn’t catch you.', 'Простите, я не расслышал.'],
  ['Lucky you!', 'Вам повезло!'],
  ['Good for you!', 'Тем лучше для вас! (часто подразумевается сарказм: «Ну-ну, рад за тебя!»)'],
  ['I’m so happy for you!', 'Я так рад за вас! (А вот это говорится абсолютно искренне)'],
  ['What do you know!', 'Кто бы мог подумать!']
]

const verbsIregul = [
  ['arise,	arose,	arisen', 'возникать'],
  ['awake,	awaked, awaked', 'будить, просыпаться'],
  ['be,	was/were,	been', 'быть'],
  ['bear,	bore,	born', 'рождать'],
  ['beat,	beat, beat', 'бить'],
  ['become, became, become', 'становиться	 '],
  ['befall, befell, befallen', 'случаться; приключаться'],
  ['begin,	began,	begun', 'начинать (-ся)'],
  ['behold,	beheld,	beheld', 'лицезреть; смотреть'],
  ['bend,	bent,	bent', 'гнуть (-ся); сгибать (-ся) '],
  ['bet,	bet,  bet', 'быть уверенным в, спорить на'],
  ['bid,	bade,	bidden', 'поручать'],
  ['bid,	bid,	bid', 'предлагать'],
  ['bind,	bound,	bound', 'связывать'],
  ['bite,	bit,	bitten', 'кусать'],
  ['bleed,	bled,	bled', 'истекать кровью'],
  ['blow,	blew,	blown', 'дуть'],
  ['break,	broke,	broken', 'ломать'],
  ['breed,	bred,	bred', 'выводить, разводить'],
  ['bring,	brought,	brought', 'приносить'],
  ['broadcast,	broadcast, broadcast', 'передавать по радио'],
  ['build,	built,	built', 'строить'],
  ['burn,	burned, burned', 'гореть, жечь'],
  ['burst,	burst,	burst', 'разрываться'],
  ['buy,	bought,	bought', 'покупать'],
  ['cast,	cast,	cast', 'бросать, кидать'],
  ['catch,	caught,	caught', 'ловить, схватить'],
  ['chide,	chided, chided', 'бранить; упрекать; журить '],
  ['choose,	chose,	chosen', 'выбирать'],
  ['cling,	clung,	clung', 'прилипать, цепляться'],
  ['clothe,	clothed, clothed', 'одеть, обеспечить одеждой'],
  ['come,	came,	come', 'приходить'],
  ['cost,	cost,	cost', 'стоить'],
  ['creep,	crept,	crept', 'ползать'],
  ['crow,	crew, crowed', 'кукарекать'],
  ['cut,	cut,	cut', 'резать'],
  ['dare,	dared,	dared', 'сметь '],
  ['deal,	dealt,	dealt', 'торговать, иметь дело'],
  ['dig,	dug,	dug', 'копать'],
  ['do,	did,	done', 'делать'],
  ['draw,	drew,	drawn	', 'тащить, рисовать'],
  ['dream,	dreamed	dreamed', '	видеть сны, мечтать'],
  ['drink,	drank,	drunk', '	пить	 '],
  ['drive,	drove,	driven', 'гнать, везти, ехать'],
  ['dwell,	dwelt, dwelt', '	обитать, останавливаться подробно	 '],
  ['eat,	ate, eaten', 'кушать'],
  ['fall,	fell,	fallen	', 'падать'],
  ['feed,	fed,	fed', 'кормить (-ся)'],
  ['feel,	felt,	felt', 'чувствовать'],
  ['fight,	fought,	fought', 'бороться, сражаться'],
  ['find,	found,	found', 'находить'],
  ['flee,	fled,	fled', 'бежать, спасаться бегством'],
  ['fling,	flung,	flung', 'кидать, бросать'],
  ['fly,	flew,	flown', 'летать'],
  ['forbid,	forbade,	forbidden', 'запрещать'],
  ['forget,	forgot,	forgotten', 'забывать'],
  ['forgive,	forgave,	forgiven', 'прощать'],
  ['forsake,	forsook,	forsaken', 'бросать; оставлять; отказываться'],
  ['freeze,	froze,	frozen	', '	замерзать, замораживать	 '],
  ['get,	got,	got', 'получать, становиться	 '],
  ['give,	gave,	given', 'давать'],
  ['go,	went,	gone', 'идти, ехать'],
  ['grind,	ground,	ground', 'точить, молоть'],
  ['grow,	grew,	grown', 'расти, выращивать	 '],
  ['hang,	hung,	hung', 'висеть (повесить картину)	 '],
  ['hang,	hanged,	hanged', 'повесить (убить)	 '],
  ['have,	had,	had', '	иметь '],
  ['hear,	heard,	heard', '	слышать	 '],
  ['hew,	hewed,	hewed', '	отрубить, отколоть; надтесывать	 '],
  ['hide,	hid,	hidden', 'прятать	 '],
  ['hit,	hit,	hit', 'ударять, поражать	 '],
  ['hold,	held,	held', 'держать	 '],
  ['hurt,	hurt,	hurt', 'повредить, ушибить'],
  ['keep,	kept,	kept', 'держать, хранить'],
  ['kneel,	knelt, knelt', 'становиться на колени	 '],
  ['knit,	knit,	knit', 'связывать, объединять	 '],
  ['know,	knew,	known', '	знать'],
  ['lay,	laid,	laid', 'класть'],
  ['lead,	led,	led', 'вести'],
  ['lean,	leaned,  leant', 'прислоняться'],
  ['leap,	leapt, leaped', 'прыгать'],
  ['learn,	learned, 	learned', 'учиться'],
  ['leave,	left,	left', 'оставлять, уезжать'],
  ['lend,	lent,	lent', 'давать в займы, одалживать'],
  ['let,	let,	let', '	позволять, сдавать в наем	 '],
  ['lie,	lay,	lain', 'лежать'],
  ['light,	lighted, lighted', 'зажигать, освещать'],
  ['lose,	lost,	lost', 'терять'],
  ['make,	made,	made', 'делать, заставлять'],
  ['mean,	meant,	meant', 'значить, подразумевать'],
  ['meet,	met,	met', 'встречать'],
  ['mow,	mowed,	mowed', 'косить (газон)'],
  ['pay,	paid,	paid', 'платить'],
  ['put,	put,	put', 'класть'],
  ['read, read/red, read/red', 'читать '],
  ['rid,	rid,	rid', '	избавляться; освобождать	 '],
  ['ride,	rode,	ridden', 'ездить верхом'],
  ['ring,	rang,	rung', 'звонить, звенеть'],
  ['rise,	rose,	risen	', '	подниматься'],
  ['run,	ran,	run', '	бежать '],
  ['saw,	sawed,	sawed', '	пилить'],
  ['say,	said,	said', 'говорить, сказать	 '],
  ['see,	saw,	seen', 'видеть	 '],
  ['seek,	sought,	sought', 'искать'],
  ['sell,	sold,	sold', 'продавать '],
  ['send,	sent,	sent', 'посылать'],
  ['set,	set,	set', 'помещать, ставить, заходить (о солнце)'],
  ['sew,	sewed,	sewed', 'шить'],
  ['shake,	shook,	shaken', 'трясти '],
  ['shed,	shed,	shed', 'проливать (слезы, кровь)'],
  ['shine,	shined, shined', 'сиять, светить	 '],
  ['shoe,	shod,	shod', 'подковать'],
  ['shoot,	shot,	shot', 'стрелять'],
  ['show,	showed,	shown	', 'показывать'],
  ['shrink,	shrank,	shrunk', 'сморщиваться, сокращаться	 '],
  ['shut,	shut,	shut', 'закрывать'],
  ['sing,	sang,	sung', 'петь'],
  ['sink,	sunk, sunk', 'погружаться, тонуть'],
  ['sit,	sat,	sat', '	сидеть'],
  ['slay,	slew,	slain', 'убить жестоким способом'],
  ['sleep,	slept,	slept', 'спать'],
  ['slide,	slid,	slid', 'скользить'],
  ['sling,	slung,	slung', 'швырять, кидать; вешать через плечо'],
  ['slink,	slunk,	slunk', 'уйти незаметно, ускользнуть'],
  ['slit,	slit,	slit', 'разрезать вдоль, расщеплять'],
  ['smell,	smelt, smelt', 'пахнуть, нюхать	 '],
  ['speak,	spoke,	spoken', 'говорить'],
  ['speed,	sped,	sped', 'спешить, ускорять'],
  ['spell,	spelt, spelt', 'писать или произносить слово по буквам	 '],
  ['spend,	spent,	spent', 'тратить'],
  ['spill,	spilled, spilled', 'проливать'],
  ['spin,	spun,	span', 'прясть, крутить, вертеться'],
  ['spit,	spat,	spat', 'плевать'],
  ['split,	split,	split	', 'раскалывать (-ся)'],
  ['spoil,	spoiled, spoiled', 'портить, баловать'],
  ['spread,	spread,	spread', 'распространять (-ся)	 '],
  ['spring,	sprang,	sprung', 'возникать, пружинить, прорастать'],
  ['stand,	stood,	stood	', 'стоять'],
  ['steal,	stole,	stolen', 'красть'],
  ['stick,	stuck,	stuck	', 'приклеивать (-ся)'],
  ['sting,	stung,	stung	', 'жалить '],
  ['stink,	stunk, stunk', 'вонять, смердеть'],
  ['stride,	strode,	stridden', 'размашисто шагать'],
  ['strike,	struck,	struck', 'ударять, бастовать'],
  ['strive,	strove,	striven	', 'стремиться '],
  ['swear,	swore,	sworn	', 'клясться, браниться'],
  ['sweep,	swept,	swept	', 'мести'],
  ['swell,	swelled,	swelled', 'пухнуть, раздуваться'],
  ['swim,	swam,	swum', 'плавать	'],
  ['swing,	swung,	swung	', 'начинать (-ся), размахивать	 '],
  ['take,	took,	taken', '	брать	'],
  ['teach,	taught,	taught', 'обучать, учить'],
  ['tear,	tore,	torn', '	рвать	'],
  ['tell,	told,	told', 'рассказывать'],
  ['think,	thought,	thought	', 'думать'],
  ['thrive,	thrived,	thrived', 'преуспевать'],
  ['throw,	threw,	thrown', 'бросать'],
  ['thrust,	thrust,	thrust', 'толкнуть неожиданно и напористо	 '],
  ['tread,	trod, trod', 'ступать, наступать'],
  ['understand,	understood,	understood', 'понимать'],
  ['undertake,	undertook,	undertaken', 'предпринять; обязываться'],
  ['wake,	woke,  woken', 'будить, просыпаться'],
  ['wear,	wore,	worn', 'носить (одежду), быть одетым в'],
  ['weave,	wove,	woven', 'ткать; выплетать '],
  ['weep,	wept,	wept', 'плакать '],
  ['wet,	wet,	wet', '	мочиться, писать (в постель)'],
  ['win,	won,	won', 'выигрывать'],
  ['wind,	wound,	wound	', 'заводить (часы), виться'],
  ['wind,	winded,	winded', 'вызвать задержку дыхания'],
  ['wring,	wrung,	wrung', 'выжимать '],
  ['write,	wrote,	written', 'писать ']
]

let count = 0;
let wordList = wordL;
let dictionaries = document.querySelectorAll('.dictionaries');

const setDictionary = () => {
  for (let dictionary of dictionaries) {
    dictionary.onchange = function () {
      if (dictionary.dataset.learn === 'verbs') {
        wordList = frasVerbs;
        count = 0;
        numbersWord.innerHTML = `<p>${count + 1} out of ${wordList.length}</p>`;
        wordEn.innerHTML = `<p>${wordList[count][0]}</p>`;
        wordRu.innerHTML = `<p>${wordList[count][1]}</p>`;

      } else if (dictionary.dataset.learn === 'phrases') {
        wordList = phrases;
        count = 0;
        numbersWord.innerHTML = `<p>${count + 1} out of ${wordList.length}</p>`;
        wordEn.innerHTML = `<p>${wordList[count][0]}</p>`;
        wordRu.innerHTML = `<p>${wordList[count][1]}</p>`;

      } else if (dictionary.dataset.learn === 'verbsIrregul') {
        wordList = verbsIregul;
        count = 0;
        numbersWord.innerHTML = `<p>${count + 1} out of ${wordList.length}</p>`;
        wordEn.innerHTML = `<p>${wordList[count][0]}</p>`;
        wordRu.innerHTML = `<p>${wordList[count][1]}</p>`;
      }
      else {
        wordList = wordL;
        count = 0;
        numbersWord.innerHTML = `<p>${count + 1} out of ${wordList.length}</p>`;
        wordEn.innerHTML = `<p>${wordList[count][0]}</p>`;
        wordRu.innerHTML = `<p>${wordList[count][1]}</p>`;
      };
    };
  };
}
setDictionary()

const wordRu = document.querySelector('.word_ru');
const wordEn = document.querySelector('.word_en');
const memoryCard = document.querySelector('.memory-card');

function translate() {
  wordEn.style.display === 'block' ? wordEn.style.display = 'none' : wordEn.style.display = 'block';
  wordRu.style.display === 'none' ? wordRu.style.display = 'block' : wordRu.style.display = 'none';
}

memoryCard.addEventListener('click', translate);

const next = document.querySelector('.next');
const prev = document.querySelector('.prev');
const numbersWord = document.querySelector('.numbersWord');

function nextWord() {
  wordEn.style.display = 'block';
  wordRu.style.display = 'none';
  count++;
  if (count == wordList.length) {
    count = 0;
  }
  numbersWord.innerHTML = `<p>${count + 1} out of ${wordList.length}</p>`;
  wordEn.innerHTML = `<p>${wordList[count][0]}</p>`;
  wordRu.innerHTML = `<p>${wordList[count][1]}</p>`;
}

function prevWord() {
  wordEn.style.display = 'block';
  wordRu.style.display = 'none';
  count--;
  if (count < 0) {
    count = wordList.length - 1;
    numbersWord.innerHTML = `<p>${count + 1} out of ${wordList.length}</p>`;
    wordEn.innerHTML = `<p>${wordList[count][0]}</p>`;
    wordRu.innerHTML = `<p>${wordList[count][1]}</p>`;
    count = wordList.length - 1;
  }
  numbersWord.innerHTML = `<p>${count + 1} out of ${wordList.length}</p>`;
  wordEn.innerHTML = `<p>${wordList[count][0]}</p>`;
  wordRu.innerHTML = `<p>${wordList[count][1]}</p>`;
}

next.addEventListener('click', nextWord);
prev.addEventListener('click', prevWord);
const textEl = document.getElementById('text');
const voiceInEl = document.getElementById('voice');
const pitchInEl = document.getElementById('pitch');
const rateInEl = document.getElementById('rate');
const volumeInEl = document.getElementById('volume');
const pitchOutEl = document.querySelector('output[for="pitch"]');
const rateOutEl = document.querySelector('output[for="rate"]');
const volumeOutEl = document.querySelector('output[for="volume"]');
const speakEl = document.getElementById('speak');

pitchInEl.addEventListener('change', updateOutputs);
rateInEl.addEventListener('change', updateOutputs);
volumeInEl.addEventListener('change', updateOutputs);
speakEl.addEventListener('click', speakText);

updateVoices();
window.speechSynthesis.onvoiceschanged = updateVoices;

function updateOutputs() {
  pitchOutEl.textContent = pitchInEl.value;
  rateOutEl.textContent = rateInEl.value;
  volumeOutEl.textContent = volumeInEl.value;
}

function updateVoices() {
  window.speechSynthesis.getVoices().forEach(voice => {
    const isAlreadyAdded = [...voiceInEl.options].some(option => option.value === voice.voiceURI);
    if (!isAlreadyAdded) {
      const option = new Option(voice.name, voice.voiceURI, voice.default, voice.default);
      voiceInEl.add(option);
    }
  });
}

function speakText() {
  window.speechSynthesis.cancel();
  const text = wordList[count][0];
  utterance = new SpeechSynthesisUtterance(text);

  if (localStorage.getItem('voice')) {
    let cat = localStorage.getItem('voice');
    console.log(utterance)

    utterance.voice = window.speechSynthesis.getVoices().find(voice => voice.voiceURI === cat);
    if (utterance.voice == undefined) {
      utterance.voice = window.speechSynthesis.getVoices().find(voice => voice.voiceURI === voiceInEl.value);
    }
  } else {
    utterance.voice = window.speechSynthesis.getVoices().find(voice => voice.voiceURI === voiceInEl.value);
  }
  utterance.pitch = pitchInEl.value;
  utterance.rate = rateInEl.value;
  utterance.volume = volumeInEl.value;
  window.speechSynthesis.speak(utterance);
}

voiceInEl.addEventListener('change', () => {
  localStorage.setItem('voice', voiceInEl.value);
});

const setting = document.querySelector('.setting');
const properties = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const close = document.querySelector('.close');


setting.addEventListener('click', () => {
  properties.style.display === 'none' ? properties.style.display = 'block' : properties.style.display = 'none';
  overlay.style.display === 'none' ? overlay.style.display = 'block' : overlay.style.display = 'none';
});

close.addEventListener('click', () => {
  properties.style.display = 'none';
  overlay.style.display = 'none';
});